In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd

In [ ]:
%cd "/content/drive/Shareddrives/예측모델_기말프로젝트/원본_데이터"

/content/drive/Shareddrives/예측모델_기말프로젝트/원본_데이터

In [ ]:
!ls

'10_서울특별시 공공자전거 이용정보(시간대별)_20190601_20191130(3).csv'
'11_서울특별시 공공자전거 이용정보(시간대별)_20190601_20191130(2).csv'
'1_서울특별시 공공자전거 이용정보(시간대별)_202006.csv'
'12_서울특별시 공공자전거 이용정보(시간대별)_20190601_20191130(1).csv'
'13_서울특별시 공공자전거 이용정보(시간대별)_201812_201905(6).csv'
'14_서울특별시 공공자전거 이용정보(시간대별)_201812_201905(5).csv'
'15_서울특별시 공공자전거 이용정보(시간대별)_201812_201905(4).csv'
'16_서울특별시 공공자전거 이용정보(시간대별)_201812_201905(3).csv'
'17_서울특별시 공공자전거 이용정보(시간대별)_201812_201905(2).csv'
'18_서울특별시 공공자전거 이용정보(시간대별)_201812_201905(1).csv'
'19_서울특별시 공공자전거 이용정보(시간대별)_201811.xlsx'
'20_서울특별시 공공자전거 이용정보(시간대별)_201810.xlsx'
'21_서울특별시 공공자전거 이용정보(시간대별)_201809.xlsx'
'2_서울특별시 공공자전거 이용정보(시간대별)_201912_202006.csv'
'22_서울특별시 공공자전거 이용정보(시간대별)_201808.xlsx'
'23_서울특별시 공공자전거 이용정보(시간대별)_201807.xlsx'
'24_서울특별시 공공자전거 이용정보(시간대별)_201806.xlsx'
'25_서울특별시 공공자전거 이용정보(시간대별)_201801_02.xlsx'
'26_서울특별시 공공자전거 이용정보(시간대별)_201803_04.xlsx'
'27_서울특별시 공공자전거 이용정보(시간대별)_201805.xlsx'
'3_서울특별시 공공자전거 이용정보(시간대별)_20190601_20191130(10).csv'
'4_서울특별시 공공자전거 이용정보(시간대별)_20190601_20191130(9).csv'
'5_서울특별시 공공자전거 이용정보(시간대별)_20190601_20191130(8).csv'
'6_서울특별시 공공자전거 이용정보(시간대별)_20190601_20191130(7).csv'
'7_서울특별시 공공자전거 이용정보(시간대별)_20190601_20191130(6).csv'
'8_서울특별시 공공자전거 이용정보(시간대별)_20190601_20191130(5).csv'
'9_서울특별시 공공자전거 이용정보(시간대별)_20190601_20191130(4).csv'
 data_extracted.csv
 사용원본데이터.zip

In [ ]:
import os

path = "./"
file_list = os.listdir(path)
file_list_xlsx = [file for file in file_list if file.endswith(".xlsx")]
file_list_csv = [file for file in file_list if file.endswith(".csv")]

In [ ]:
print ("file_list_csv: {}".format(file_list_csv))

file_list_csv: ['13_서울특별시 공공자전거 이용정보(시간대별)_201812_201905(6).csv', '1_서울특별시 공공자전거 이용정보(시간대별)_202006.csv', '2_서울특별시 공공자전거 이용정보(시간대별)_201912_202006.csv', '3_서울특별시 공공자전거 이용정보(시간대별)_20190601_20191130(10).csv', '4_서울특별시 공공자전거 이용정보(시간대별)_20190601_20191130(9).csv', '5_서울특별시 공공자전거 이용정보(시간대별)_20190601_20191130(8).csv', '7_서울특별시 공공자전거 이용정보(시간대별)_20190601_20191130(6).csv', '6_서울특별시 공공자전거 이용정보(시간대별)_20190601_20191130(7).csv', '8_서울특별시 공공자전거 이용정보(시간대별)_20190601_20191130(5).csv', '9_서울특별시 공공자전거 이용정보(시간대별)_20190601_20191130(4).csv', '10_서울특별시 공공자전거 이용정보(시간대별)_20190601_20191130(3).csv', '11_서울특별시 공공자전거 이용정보(시간대별)_20190601_20191130(2).csv', '15_서울특별시 공공자전거 이용정보(시간대별)_201812_201905(4).csv', '14_서울특별시 공공자전거 이용정보(시간대별)_201812_201905(5).csv', '12_서울특별시 공공자전거 이용정보(시간대별)_20190601_20191130(1).csv', '16_서울특별시 공공자전거 이용정보(시간대별)_201812_201905(3).csv', '17_서울특별시 공공자전거 이용정보(시간대별)_201812_201905(2).csv', '18_서울특별시 공공자전거 이용정보(시간대별)_201812_201905(1).csv']

In [ ]:
print ("file_list_xlsx: {}".format(file_list_xlsx))

file_list_xlsx: ['19_서울특별시 공공자전거 이용정보(시간대별)_201811.xlsx', '20_서울특별시 공공자전거 이용정보(시간대별)_201810.xlsx', '21_서울특별시 공공자전거 이용정보(시간대별)_201809.xlsx', '23_서울특별시 공공자전거 이용정보(시간대별)_201807.xlsx', '22_서울특별시 공공자전거 이용정보(시간대별)_201808.xlsx', '24_서울특별시 공공자전거 이용정보(시간대별)_201806.xlsx', '25_서울특별시 공공자전거 이용정보(시간대별)_201801_02.xlsx', '27_서울특별시 공공자전거 이용정보(시간대별)_201805.xlsx', '26_서울특별시 공공자전거 이용정보(시간대별)_201803_04.xlsx']

In [ ]:
dfs_excel = []

for file in file_list_xlsx:
    df_excel = pd.read_excel(file)
    df_excel = df_excel[df_excel['대여소번호']==1308]
    dfs_excel.append(df_excel)
    
df_excel = pd.concat(dfs_excel, ignore_index=True)

In [ ]:
dfs_csv = []

for file in file_list_csv:
    df_csv = pd.read_csv(file, encoding= 'cp949')
    df_csv = df_csv[df_csv['대여소번호']==1308]
    dfs_csv.append(df_csv)

df_csv = pd.concat(dfs_csv, ignore_index=True)

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (8,9) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [ ]:
print('df_excel')
print(df_excel.shape)
print(df_excel.head())

df_excel
(14921, 12)
        대여일자  대여시간  대여소번호            대여소명  ...      운동량    탄소량    이동거리  이동시간
0 2018-11-01     0   1308   안암로터리 버스정류장 앞  ...    82.83   0.62    2660    15
1 2018-11-01     1   1308   안암로터리 버스정류장 앞  ...  3152.36  24.62  106140     6
2 2018-11-01     2   1308   안암로터리 버스정류장 앞  ...    42.17   0.35    1500    12
3 2018-11-01     3   1308   안암로터리 버스정류장 앞  ...    97.04   0.87    3770    19
4 2018-11-01     6   1308   안암로터리 버스정류장 앞  ...    33.98   0.36    1560    11

[5 rows x 12 columns]

In [ ]:
print('df_csv')
print(df_csv.shape)
print(df_csv.head())

df_csv
(44999, 12)
         대여일자  대여시간  대여소번호                 대여소명  ...    운동량   탄소량    이동거리  사용시간
0  2019-02-27     0   1308  1308. 안암로터리 버스정류장 앞  ...   39.9  0.36  1550.0     9
1  2019-02-27     0   1308  1308. 안암로터리 버스정류장 앞  ...  43.52  0.36  1570.0     7
2  2019-02-27     1   1308  1308. 안암로터리 버스정류장 앞  ...  42.77  0.52  2250.0    12
3  2019-02-27     1   1308  1308. 안암로터리 버스정류장 앞  ...  38.49  0.25  1080.0    57
4  2019-02-27     1   1308  1308. 안암로터리 버스정류장 앞  ...  69.11  0.64  2770.0    13

[5 rows x 12 columns]

In [ ]:
df = pd.concat([df_excel, df_csv], ignore_index=True)

In [ ]:
print('df')
print(df.shape)
print(df.head())

df
(59920, 13)
                  대여일자  대여시간  대여소번호  ...      이동거리  이동시간 사용시간
0  2018-11-01 00:00:00     0   1308  ...    2660.0  15.0  NaN
1  2018-11-01 00:00:00     1   1308  ...  106140.0   6.0  NaN
2  2018-11-01 00:00:00     2   1308  ...    1500.0  12.0  NaN
3  2018-11-01 00:00:00     3   1308  ...    3770.0  19.0  NaN
4  2018-11-01 00:00:00     6   1308  ...    1560.0  11.0  NaN

[5 rows x 13 columns]

In [ ]:
df.to_csv('data_extracted.csv')

In [ ]:
df.to_csv('data_extracted(cp949).csv', encoding = 'cp949')

### STOP

In [ ]:
data = pd.read_csv('2_서울특별시 공공자전거 이용정보(시간대별)_201912_202006.csv', encoding= 'cp949')

In [ ]:
data.shape

(6894866, 12)

In [ ]:
data.head()

         대여일자  대여시간  대여소번호                     대여소명  ...     운동량   탄소량    이동거리  사용시간
0  2019-12-01     0    504           504. 신자초교입구교차로  ...   74.84  0.67  2880.0    17
1  2019-12-01     0   1029             1029. 롯데 시네마  ...  246.71  2.06  8900.0    45
2  2019-12-01     0   1153  1153. 발산역 1번, 9번 인근 대여소  ...   25.60  0.23  1010.0    12
3  2019-12-01     0    512         512. 뚝섬역 1번 출구 옆  ...   78.59  0.73  3150.0    17
4  2019-12-01     0   1528          1528. 삼각산동 주민센터  ...   26.15  0.22   930.0     5

[5 rows x 12 columns]

In [ ]:
data.tail()

               대여일자  대여시간  대여소번호  ...   탄소량    이동거리 사용시간
6894861  2020-05-31    23   1610  ...  1.65  7120.0   34
6894862  2020-05-31    23   2318  ...  1.37  5910.0   40
6894863  2020-05-31    23   2329  ...  0.00     0.0   20
6894864  2020-05-31    23   1450  ...  0.00     0.0    5
6894865  2020-05-31    23   2418  ...  0.00     0.0   12

[5 rows x 12 columns]

## 2017년 추가

In [ ]:
import pandas as pd
import numpy as np
import os, shutil
from glob import glob
from tqdm import tqdm
import time
import logging

In [ ]:
logger = logging.getLogger(__name__)
logging.basicConfig(format='%(asctime)s - %(message)s', level=logging.INFO)

base_dir = '/content/drive/Shareddrives/예측모델_기말프로젝트/원본_데이터/folder_2017'
data_2017 = glob(os.path.join(base_dir, "*.csv"))
data_2017

['/content/drive/Shareddrives/예측모델_기말프로젝트/원본_데이터/folder_2017/2017_1.csv',
 '/content/drive/Shareddrives/예측모델_기말프로젝트/원본_데이터/folder_2017/2017_3.csv',
 '/content/drive/Shareddrives/예측모델_기말프로젝트/원본_데이터/folder_2017/2017_2.csv',
 '/content/drive/Shareddrives/예측모델_기말프로젝트/원본_데이터/folder_2017/2017_6.csv',
 '/content/drive/Shareddrives/예측모델_기말프로젝트/원본_데이터/folder_2017/2017_5.csv',
 '/content/drive/Shareddrives/예측모델_기말프로젝트/원본_데이터/folder_2017/2017_4.csv']

In [ ]:
# set clean columns
data1 = pd.read_csv(data_2017[0], encoding = 'euc-kr')
clean_columns = list(map(lambda r: r.replace('\'', ''), list(data1.columns)))

In [ ]:
clean_columns

['대여일자',
 '대여시간',
 '대여소번호',
 '대여소',
 '대여구분코드',
 '성별',
 '연령대코드',
 '이용건수',
 '운동량',
 '탄소량',
 '이동거리(M)',
 '이동시간(분)']

In [ ]:
# ------------------------
#     DATA CLEANSING
# ------------------------
result_df = pd.DataFrame(columns = clean_columns)
for file in tqdm(data_2017, desc = "DATA CONCAT"):
    # read
    to_get = pd.read_csv(file, encoding = 'euc-kr')

    # change columns
    to_get.columns = clean_columns
    
    # change values
    for i in range(7):
        to_get.iloc[:, i] = to_get.iloc[:, i].str.replace('\'', '')
    
    to_get_1308 = to_get.loc[to_get['대여소번호'] == '1308', :]    
    logger.info(f"extracted data length: {to_get_1308.shape[0]}")
    
    result_df = pd.concat([result_df, to_get_1308], axis = 0)

DATA CONCAT:   0%|          | 0/6 [00:00<?, ?it/s]2020-12-03 04:04:10,423 - extracted data length: 0
DATA CONCAT:  17%|█▋        | 1/6 [00:05<00:29,  5.95s/it]/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)
2020-12-03 04:04:13,138 - extracted data length: 1230
DATA CONCAT:  33%|███▎      | 2/6 [00:08<00:19,  4.98s/it]2020-12-03 04:04:17,841 - extracted data length: 1247
DATA CONCAT:  50%|█████     | 3/6 [00:13<00:14,  4.90s/it]2020-12-03 04:04:21,431 - extracted data length: 1900
DATA CONCAT:  67%|██████▋   | 4/6 [00:17<00:09,  4.58s/it]2020-12-03 04:04:26,003 - extracted data length: 1924
DATA CONCAT:  83%|████████▎ | 5/6 [00:21<00:04,  4.51s/it]2020-12-03 04:04:30,276 - extracted data length: 1826
DATA CONCAT: 100%|██████████| 6/6 [00:25<00:00,  4.30s/it]

In [ ]:
anam_sorted = result_df.sort_values(by = '대여일자').reset_index(drop = True)
anam_sorted.head(5)

         대여일자 대여시간 대여소번호             대여소  ...     운동량   탄소량 이동거리(M) 이동시간(분)
0  2017-06-21   18  1308   안암로터리 버스정류장 앞  ...  242.73  2.19    9430      53
1  2017-06-21   18  1308   안암로터리 버스정류장 앞  ...  131.79  1.19    5120      22
2  2017-06-21   18  1308   안암로터리 버스정류장 앞  ...  291.61  2.73   11780     113
3  2017-06-21   19  1308   안암로터리 버스정류장 앞  ...  361.13  3.25   14030      57
4  2017-06-21   21  1308   안암로터리 버스정류장 앞  ...  212.61  1.78    7670      55

[5 rows x 12 columns]

In [ ]:
anam_sorted.loc[:, '이용건수'] = pd.to_numeric(anam_sorted.loc[:, '이용건수'])

In [ ]:
anam_sum = anam_sorted.groupby('대여일자', as_index = False).sum()
anam_fin = anam_sum.loc[:, ['대여일자', '이용건수']]
anam_fin.columns = ['date', 'cnt']

In [ ]:
print(len(anam_fin))

193

## 기존 데이터에 concat

In [ ]:
df_after = pd.read_csv('/content/drive/Shareddrives/예측모델_기말프로젝트/분석_데이터/daily_user_cnt.csv', encoding = 'cp949')
print(len(df_after))

730

In [ ]:
df_fin = pd.concat([df_after, anam_fin], axis = 0).sort_values(by = 'date').reset_index(drop = True)
df_fin.head(5)

         date  cnt
0  2017-06-21   13
1  2017-06-22   40
2  2017-06-23   39
3  2017-06-24   28
4  2017-06-25   28

In [ ]:
# write file
df_fin.to_csv('/content/drive/Shareddrives/예측모델_기말프로젝트/분석_데이터/daily_user_cnt_tot.csv')

## Holiday / 전처리

In [ ]:
import holidays
kor_holidays = holidays.Korea()

In [ ]:
holiday_list = ['-'.join((str(holi.year), str(holi.month).zfill(2), str(holi.day).zfill(2))) for year in range(2017, 2021) for holi in holidays.KR(years=year)]

In [ ]:
holiday_df = pd.DataFrame({'date': holiday_list, 'is_holiday': 1})
holiday_df.head(5)

         date  is_holiday
0  2017-01-01           1
1  2017-01-02           1
2  2017-01-27           1
3  2017-01-28           1
4  2017-01-29           1

In [ ]:
holiday_joined = pd.merge(df_fin, holiday_df, on = 'date', how = 'left').fillna(0).astype({'is_holiday': int})

In [ ]:
holiday_joined

           date  cnt  is_holiday
0    2017-06-21   13           0
1    2017-06-22   40           0
2    2017-06-23   39           0
3    2017-06-24   28           0
4    2017-06-25   28           0
..          ...  ...         ...
918  2019-12-27   81           0
919  2019-12-28   79           0
920  2019-12-29   61           0
921  2019-12-30   77           0
922  2019-12-31   39           0

[923 rows x 3 columns]

In [ ]:
holiday_joined[['year','month', 'day']] = holiday_joined.date.str.split("-",expand=True,)
holiday_joined['weekday'] = pd.to_datetime(holiday_joined['date']).dt.weekday
holiday_joined['weeknum'] = pd.to_datetime(holiday_joined['date']).dt.week

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: FutureWarning: Series.dt.weekofyear and Series.dt.week have been deprecated.  Please use Series.dt.isocalendar().week instead.
  This is separate from the ipykernel package so we can avoid doing imports until

In [ ]:
holiday_joined.loc[holiday_joined['is_holiday']==1,:].head(3)

           date  cnt  is_holiday  year month day  weekday  weeknum
54   2017-08-15   11           1  2017    08  15        1       33
103  2017-10-03   54           1  2017    10  03        1       40
104  2017-10-04   39           1  2017    10  04        2       40

In [ ]:
holiday_joined.shape

(923, 8)

In [ ]:
holiday_joined.to_csv('/content/drive/Shareddrives/예측모델_기말프로젝트/분석_데이터/daily_usr_cnt_with_holiday_tot.csv')